name: Git sync to other repo

on: push

jobs:
  sync:
    name: Sync to bitbucket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: bash
        env:
          PUSH_ACCESS_TOKEN: ${{ secrets.PUSH_ACCESS_TOKEN }}
        run: |
          pwd && ls
          echo 'remote add'
          git remote add bitbucket "${PUSH_REPO}"
          echo 'git pull'
          git fetch bitbucket
          echo 'git config'
          git config user.email "${PUSH_ACCESS_TOKEN}"
          echo 'git push'
          git push bitbucket
          echo 'finish'
