name: Git sync to other repo

on: push

jobs:
  my-job:
    name: Sync to bitbucket
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          PUSH_ACCESS_TOKEN: ${{ secrets.PUSH_ACCESS_TOKEN }}
        run: |
          git clone https://github.com/zuoez02/siyuan-plugins
          cd siyuan-plugins
          git remote add bitbucket "${PUSH_REPO}"
          git config user.email "${PUSH_ACCESS_TOKEN}"
          git push bitbucket
