name: Git sync to other repo

on: push

jobs:
  my-job:
    name: Sync to bitbucket
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.PUSH_ACCESS_TOKEN }}
        run: |
          git remote add bitbucket "https://x-token-auth:${SUPER_SECRET}@bitbucket.org/siyuan-plugin/siyuan-plugins.git"
          git config user.name zuoez02
          git config user.email zuoez02@outlook.com
          git push bitbucket
